"""empty message

Revision ID: 487550685afe
Revises: 
Create Date: 2023-06-19 13:43:58.003928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487550685afe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.String(length=50), nullable=True),
    sa.Column('card_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('permission', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Year',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('Month',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['year'], ['Year.year'], ),
    sa.PrimaryKeyConstraint('year', 'month')
    )
    with op.batch_alter_table('Month', schema=None) as batch_op:
        batch_op.create_index('ix_month_id', ['month'], unique=False)

    op.create_table('User_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=30), nullable=True),
    sa.Column('login_timestamp', sa.DateTime(), nullable=True),
    sa.Column('logout_timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('department', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('manager', sa.String(length=30), nullable=True),
    sa.Column('device', sa.String(length=50), nullable=True),
    sa.Column('serial_number', sa.String(length=50), nullable=True),
    sa.Column('object', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('exit_date', sa.DateTime(), nullable=True),
    sa.Column('exit', sa.Boolean(), nullable=True),
    sa.Column('approve', sa.Boolean(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['Card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Day',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['month'], ['Month.month'], ),
    sa.ForeignKeyConstraint(['year'], ['Year.year'], ),
    sa.PrimaryKeyConstraint('year', 'month', 'day')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Day')
    op.drop_table('Visitor')
    op.drop_table('User_log')
    with op.batch_alter_table('Month', schema=None) as batch_op:
        batch_op.drop_index('ix_month_id')

    op.drop_table('Month')
    op.drop_table('Year')
    op.drop_table('User')
    op.drop_table('Card')
    # ### end Alembic commands ###
